### PR TITLE
Customize files minified path

### PR DESCRIPTION
**Pull request by daycry**

### CODE REVIEW

**Comment by michalsn** [comment]
Please pull the original code from this repo and run: `composer test`, then run the same command on your copy after your changes. The tests were passing just fine before your changes.

I see that you removed some example files used in the tests. That might be a good starting point to get the tests working again.

**Comment by daycry** [comment]
If you see my Code, you can see that before run deploy command I remove old
assets files.

Maybe, I should check if the same directory before remove It.

It is very important for assets control.

I will see again the unit tests, although I think are deprecated with my
changes.

Thanks.

**Comment by michalsn** [comment]
I'll put together a new release over the weekend.

**Comment by daycry** [comment]
Perfect.

Thank you!!

**Pull request merged**
